services:
  app:
    build:
      context: .
    image: sai-pallavi-image
    container_name: himalayan-container
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - vedant-network
networks:
  vedant-network:
